name: Build

on:
  push:
    branches: [main, next-gen]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test and build
        shell: bash
        run: |
          chmod +x kotlin
          ./kotlin test -m desktop
          ./kotlin build
